# Generated by Django 3.2.14 on 2024-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Contact Owner'),
        ),
    ]
