# Generated by Django 5.0.6 on 2024-05-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Experience Owner'),
        ),
    ]
