# Generated by Django 3.2.14 on 2024-05-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Contact Owner'),
        ),
    ]
