# Generated by Django 3.2.14 on 2024-05-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_experience_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Contact Owner'),
        ),
        migrations.AddField(
            model_name='skills',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Contact Owner'),
        ),
    ]
