# Generated by Django 3.2.14 on 2024-05-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20240509_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='manan', max_length=100, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='talwar', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
