# Generated by Django 3.2.14 on 2024-05-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_jobs_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='specifications',
            field=models.TextField(blank=True),
        ),
    ]
